import Link from "next/link";
import { CorporatePageHeader, CorporatePanel, EmptyState, ErrorState, FilterBar, PermissionState, StatusBadge } from "@/src/components/corporate/corporate-ui";
import { hasCorporatePermission } from "@/src/features/corporate/authorization";
import { requireCorporateSession } from "@/src/features/corporate/session";
import { getCorporateStorage } from "@/src/features/corporate/storage";

export default async function IntegrationsPage() {
  const session = await requireCorporateSession(); if (!hasCorporatePermission(session, "VIEW_RECOVERY")) return <PermissionState />;
  const deliveries = await getCorporateStorage().getDeliveryIntents(session).catch(() => null);
  return <div className="corporate-main-stack"><CorporatePageHeader eyebrow="Delivery recovery" title="Integrations & recovery" description="Separate pending, failed, and unknown outcomes so operators never receive invented confirmation." />{!deliveries ? <ErrorState title="Recovery records could not be loaded" description="The delivery source is unavailable. Do not retry an uncertain external operation from this screen." retryHref="/corporate/administration/integrations" /> : <CorporatePanel title="Delivery intents" description="Retries must reuse the original operation identity."><FilterBar resultCount={deliveries.length}><label className="corporate-field"><span>Outcome</span><select><option>Needs attention</option><option>Pending</option><option>Retry due</option><option>Unknown outcome</option><option>Delivered</option></select></label></FilterBar>{deliveries.length ? <div className="corporate-table-region" role="region" aria-label="Delivery recovery records" tabIndex={0}><table className="corporate-table"><caption className="sr-only">Corporate delivery and recovery records</caption><thead><tr><th scope="col">Operation</th><th scope="col">Channel</th><th scope="col">Outcome</th><th scope="col">Attempts</th><th scope="col">Owner</th></tr></thead><tbody>{deliveries.map((item) => <tr key={item.id}><th scope="row"><Link href={item.href}><small>{item.recordId}</small><strong>{item.summary}</strong></Link></th><td>{item.channel}</td><td><StatusBadge tone={item.status === "DELIVERED" ? "success" : item.status === "UNKNOWN_OUTCOME" || item.status === "NEEDS_REVIEW" ? "danger" : "waiting"}>{item.status.replaceAll("_", " ")}</StatusBadge></td><td>{item.attempts}</td><td>{item.ownerTeamId}</td></tr>)}</tbody></table></div> : <EmptyState title="No delivery recovery work" description="Failed or uncertain delivery appears here after a committed operation creates a durable delivery intent." />}</CorporatePanel>}</div>;
}
