import assert from "node:assert/strict";
import test from "node:test";
import fs from "node:fs";
import path from "node:path";

const component = fs.readFileSync(path.resolve("src/components/public/operator-proof-rail.tsx"), "utf8");
const mobileComponent = fs.readFileSync(path.resolve("src/components/public/operator-proof-mobile-disclosure.tsx"), "utf8");
const styles = fs.readFileSync(path.resolve("src/app/globals.css"), "utf8");

test("mobile operator-proof sequence uses a scan-first single-open disclosure stack", () => {
  assert.match(component, /MobileOperatorDisclosureList/);
  assert.doesNotMatch(component, /"use client"|useState/);
  assert.match(mobileComponent, /operator-proof-mobile-list/);
  assert.match(component, /operator-proof-section/);
  assert.doesNotMatch(component, /operator-proof-mobile-connector/);
  assert.doesNotMatch(styles, /operator-proof-mobile-connector/);
  assert.match(mobileComponent, /operator-proof-grid operator-proof-mobile-list/);
  assert.doesNotMatch(component, /openPillar|ChevronDown|grid-rows-\[1fr\]/);
  assert.match(component, /proposition: string/);
  assert.match(component, /description: string/);
  assert.match(component, /operationalFact\?:/);
  assert.match(component, /\{pillar\.proposition\}/);
  assert.match(mobileComponent, /const \[expandedPillar, setExpandedPillar\] = useState<string \| null>\(null\)/);
  assert.match(mobileComponent, /aria-expanded=\{isExpanded\}/);
  assert.match(mobileComponent, /aria-controls=\{detailId\}/);
  assert.match(mobileComponent, /role="region"/);
  assert.match(mobileComponent, /operator-proof-mobile-disclosure/);
  assert.match(mobileComponent, /\{isExpanded \? "−" : "\+"\}/);
  assert.match(mobileComponent, /\{pillar\.description\}/);
  assert.match(mobileComponent, /\{pillar\.operationalFact\.value\}/);
  assert.doesNotMatch(mobileComponent, /mobileDescription|mobileDetail/);
  assert.match(mobileComponent, /rounded-2xl border border-bds-teal-dark\/10 bg-white shadow-sm text-left/);
  assert.match(mobileComponent, /touch-target flex w-full items-center justify-between gap-4 px-4 py-3/);
  assert.match(mobileComponent, /border-t border-bds-teal-dark\/10 px-4 pb-4 pt-3/);
  assert.doesNotMatch(mobileComponent, /onScroll=\{handleCarouselScroll\}/);
  assert.doesNotMatch(mobileComponent, /scrollToPillar\(pillar\.number\)/);
  assert.doesNotMatch(mobileComponent, /Operator model carousel controls/);
  assert.doesNotMatch(mobileComponent, /autoplay|setInterval|requestAnimationFrame/);
  assert.doesNotMatch(styles, /scroll-snap-type: x mandatory/);
  assert.doesNotMatch(styles, /scroll-snap-align: center/);
  assert.match(styles, /\.operator-proof-mobile-list \{\s*display: grid;/);
  assert.match(styles, /\.operator-proof-section \{\s*padding-block: var\(--space-8\);/);
  assert.match(styles, /\.operator-proof-mobile-cta > div > p \{\s*margin-top: var\(--space-2\);/);
  assert.match(styles, /@media \(prefers-reduced-motion: no-preference\)/);
  assert.match(styles, /animation: operator-proof-disclosure-enter 160ms ease-out/);
  assert.match(styles, /translateY\(-0\.125rem\)/);
  assert.match(styles, /\.operator-proof-mobile-disclosure \{\s*animation: none !important;/);
  assert.match(mobileComponent, /text-\[11px\] font-bold uppercase tracking-\[0\.14em\] text-\[#1C5F56\]/);
  assert.match(mobileComponent, /pillar\.category\.replace\("THE ", ""\)/);
  assert.match(mobileComponent, /text-base font-bold leading-tight text-\[#1C5F56\] text-balance/);
  assert.match(mobileComponent, /touch-target min-h-11 btn-primary w-full/);
  assert.match(mobileComponent, /<CtaWithMicrocopy/);
  assert.match(mobileComponent, /microcopy=\{ctaMicrocopy\}/);
});
