import Link from "next/link";
import { CorporatePageHeader, CorporatePanel, EmptyState, ErrorState, FilterBar, PermissionState, StatusBadge } from "@/src/components/corporate/corporate-ui";
import { getCorporateInquiries } from "@/src/features/corporate/inquiries";
import { hasCorporatePermission } from "@/src/features/corporate/authorization";
import { requireCorporateSession } from "@/src/features/corporate/session";

export default async function CorporateInquiriesPage({ searchParams }: { searchParams: Promise<{ q?: string | string[]; view?: string | string[] }> }) {
  const session = await requireCorporateSession();
  if (!hasCorporatePermission(session, "VIEW_INQUIRIES")) return <PermissionState description="Your current corporate access does not include prospective franchise inquiries." />;
  const query = await searchParams;
  const q = typeof query.q === "string" ? query.q.trim().toLowerCase() : "";
  const view = typeof query.view === "string" ? query.view : "open";
  const loaded = await getCorporateInquiries(session).catch(() => null);
  const inquiries = loaded?.filter((inquiry) => (view === "routing" ? inquiry.routing.status !== "ROUTED" : view === "mine" ? inquiry.workflow.assignedToUserId === session.userId && inquiry.workflow.status !== "CLOSED" : view === "closed" ? inquiry.workflow.status === "CLOSED" : inquiry.workflow.status !== "CLOSED") && (!q || `${inquiry.id} ${String(inquiry.payload.marketInterest || "")} ${inquiry.routing.teamId}`.toLowerCase().includes(q))) ?? null;
  return <div className="corporate-main-stack"><CorporatePageHeader eyebrow="Franchise development" title="Franchise inquiries" description="Prospective candidate inquiries are routed by target market, owned by a staffed team, and kept separate from operator requests." />{!inquiries ? <ErrorState title="Inquiries could not be loaded" description="The durable inquiry source is unavailable. No routing or ownership was changed." retryHref="/corporate/inquiries" /> : <CorporatePanel title="Inquiry queue" description="Target market determines the primary region. Classification is a triage suggestion, never an automatic qualification."><FilterBar resultCount={inquiries.length}><label className="corporate-field"><span>Search</span><input name="q" type="search" defaultValue={q} placeholder="Reference, target market, or team" /></label><label className="corporate-field"><span>View</span><select name="view" defaultValue={view}><option value="open">Open inquiries</option><option value="routing">Needs routing</option><option value="mine">Assigned to me</option><option value="closed">Closed</option></select></label></FilterBar>{inquiries.length ? <div className="corporate-table-region" role="region" aria-label="Franchise inquiry queue" tabIndex={0}><table className="corporate-table"><caption className="sr-only">Prospective franchise inquiries in the authorized corporate scope</caption><thead><tr><th scope="col">Inquiry</th><th scope="col">Target market</th><th scope="col">Routing</th><th scope="col">Owner</th><th scope="col">Workflow</th><th scope="col">Delivery</th></tr></thead><tbody>{inquiries.map((inquiry) => <tr key={inquiry.id}><th scope="row"><Link href={`/corporate/inquiries/${encodeURIComponent(inquiry.id)}`}><small>{inquiry.id}</small><strong>{hasCorporatePermission(session, "VIEW_INQUIRY_PII", inquiry.routing.regionId ? { regionId: inquiry.routing.regionId } : {}) ? `${String(inquiry.payload.firstName || "Candidate")} ${String(inquiry.payload.lastName || "")}` : "Protected candidate"}</strong></Link></th><td>{String(inquiry.payload.marketInterest || "Not recorded")}</td><td><StatusBadge tone={inquiry.routing.status === "ROUTED" ? "success" : "waiting"}>{inquiry.routing.status.replaceAll("_", " ")}</StatusBadge><small>{inquiry.routing.regionId || inquiry.routing.teamId}</small></td><td>{inquiry.workflow.assignedToName || "Unassigned"}</td><td>{inquiry.workflow.status.replaceAll("_", " ")}</td><td>{inquiry.deliveryStatus}</td></tr>)}</tbody></table></div> : <EmptyState title="No inquiries in this view" description="New inquiries appear after durable persistence and region routing." />}</CorporatePanel>}</div>;
}
