import Link from "next/link";
import { CORPORATE_BUNDLE_LABELS, hasCorporatePermission } from "@/src/features/corporate/authorization";
import { requireCorporateSession } from "@/src/features/corporate/session";
import { getCorporateStorage } from "@/src/features/corporate/storage";
import { CorporatePageHeader, CorporatePanel, EmptyState, ErrorState, FilterBar, PermissionState, StatusBadge } from "@/src/components/corporate/corporate-ui";

export default async function CorporateDirectoryPage({ searchParams }: { searchParams: Promise<{ tab?: string | string[] }> }) {
  const session = await requireCorporateSession();
  if (!hasCorporatePermission(session, "VIEW_DIRECTORY")) return <PermissionState description="Your current corporate access does not include the directory." />;
  const query = await searchParams;
  const tab = typeof query.tab === "string" ? query.tab : "locations";
  const storage = getCorporateStorage();
  const loaded = await Promise.all([storage.getOrganizations(session), storage.getLocations(session), storage.getPeople(session)]).catch(() => null);
  return <div className="corporate-main-stack"><CorporatePageHeader eyebrow="Portfolio records" title="Directory" description="Find permitted organizations, locations, and people without treating names as authorization." actions={hasCorporatePermission(session, "MANAGE_LOCATIONS") ? <Link href="/corporate/directory/locations/new" className="corporate-button">Add location</Link> : undefined} />{!loaded ? <ErrorState title="Directory could not be loaded" description="Authorized portfolio records are temporarily unavailable." retryHref="/corporate/directory" /> : <CorporatePanel title="Authorized directory" description="The directory shows only records covered by your current memberships."><nav aria-label="Directory sections" className="corporate-tablist"><Link href="/corporate/directory?tab=locations" aria-current={tab === "locations" ? "page" : undefined}>Locations</Link><Link href="/corporate/directory?tab=organizations" aria-current={tab === "organizations" ? "page" : undefined}>Organizations</Link><Link href="/corporate/directory?tab=people" aria-current={tab === "people" ? "page" : undefined}>People</Link></nav><FilterBar resultCount={tab === "people" ? loaded[2].length : tab === "organizations" ? loaded[0].length : loaded[1].length}><label className="corporate-field"><span>Search {tab}</span><input type="search" placeholder="Name, code, or identity" /></label></FilterBar>
    {tab === "organizations" ? (loaded[0].length ? <div className="corporate-table-region" tabIndex={0} role="region" aria-label="Organizations"><table className="corporate-table"><caption className="sr-only">Permitted organizations</caption><thead><tr><th scope="col">Organization</th><th scope="col">Verification</th><th scope="col">Locations</th></tr></thead><tbody>{loaded[0].map((item) => <tr key={item.id}><th scope="row"><Link href={`/corporate/directory/organizations/${encodeURIComponent(item.id)}`}><small>{item.id}</small><strong>{item.name}</strong></Link></th><td><StatusBadge tone={item.verificationStatus === "VERIFIED" ? "success" : "waiting"}>{item.verificationStatus}</StatusBadge></td><td>{item.locationIds.length}</td></tr>)}</tbody></table></div> : <EmptyState title="No organizations in this scope" description="An access steward can review your assigned portfolio." />) : tab === "people" ? (loaded[2].length ? <div className="corporate-table-region" tabIndex={0} role="region" aria-label="People"><table className="corporate-table"><caption className="sr-only">Permitted people</caption><thead><tr><th scope="col">Person</th><th scope="col">Status</th><th scope="col">Access bundles</th><th scope="col">Updated</th></tr></thead><tbody>{loaded[2].map((item) => <tr key={item.id}><th scope="row"><Link href={`/corporate/directory/people/${encodeURIComponent(item.id)}`}><small>{item.email}</small><strong>{item.displayName}</strong></Link></th><td><StatusBadge tone={item.status === "ACTIVE" ? "success" : item.status === "SUSPENDED" ? "danger" : "waiting"}>{item.status}</StatusBadge></td><td>{item.memberships.map((membership) => CORPORATE_BUNDLE_LABELS[membership.bundle]).join(", ") || "None"}</td><td>{item.updatedAt ? <time dateTime={item.updatedAt}>{new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(new Date(item.updatedAt))}</time> : "Unavailable"}</td></tr>)}</tbody></table></div> : <EmptyState title="No people in this scope" description="People appear after a server-owned membership is available." />) : (loaded[1].length ? <div className="corporate-table-region" tabIndex={0} role="region" aria-label="Locations"><table className="corporate-table"><caption className="sr-only">Permitted locations</caption><thead><tr><th scope="col">Location</th><th scope="col">Organization</th><th scope="col">Market</th><th scope="col">Status</th></tr></thead><tbody>{loaded[1].map((item) => <tr key={item.id}><th scope="row"><Link href={`/corporate/directory/locations/${encodeURIComponent(item.id)}`}><small>{item.code}</small><strong>{item.name}</strong></Link></th><td>{item.organizationId || "Unverified"}</td><td>{item.market || "Not recorded"}</td><td><StatusBadge tone={item.status === "ACTIVE" ? "success" : "waiting"}>{item.status}</StatusBadge></td></tr>)}</tbody></table></div> : <EmptyState title="No locations in this scope" description="An access steward can review your assigned portfolio." />)}
  </CorporatePanel>}</div>;
}
