import { CorporatePageHeader, CorporatePanel, EmptyState, ErrorState, FilterBar, PermissionState, StatusBadge } from "@/src/components/corporate/corporate-ui";
import { hasCorporatePermission } from "@/src/features/corporate/authorization";
import { requireCorporateSession } from "@/src/features/corporate/session";
import { getCorporateStorage } from "@/src/features/corporate/storage";

export default async function AuditPage() {
  const session = await requireCorporateSession(); if (!hasCorporatePermission(session, "VIEW_AUDIT")) return <PermissionState />;
  const events = await getCorporateStorage().getAuditEvents(session).catch(() => null);
  return <div className="corporate-main-stack"><CorporatePageHeader eyebrow="Traceability" title="Audit" description="Search committed actions by actor, record, time, and safe field changes. Events are read-only." />{!events ? <ErrorState title="Audit could not be loaded" description="The audit source is unavailable." retryHref="/corporate/administration/audit" /> : <CorporatePanel title="Recorded events"><FilterBar resultCount={events.length}><label className="corporate-field"><span>Record or actor</span><input type="search" placeholder="Reference, command, or actor" /></label><label className="corporate-field"><span>Action</span><select><option>All actions</option></select></label></FilterBar>{events.length ? <div className="corporate-table-region" role="region" aria-label="Corporate audit events" tabIndex={0}><table className="corporate-table"><caption className="sr-only">Corporate audit events</caption><thead><tr><th scope="col">Event</th><th scope="col">Actor</th><th scope="col">Action</th><th scope="col">Version</th><th scope="col">Time</th></tr></thead><tbody>{events.map((event) => <tr key={event.id}><th scope="row"><small>{event.recordType}</small><strong>{event.recordId}</strong></th><td>{event.actorName}</td><td><StatusBadge>{event.action}</StatusBadge></td><td>{event.previousVersion ?? "—"} → {event.nextVersion}</td><td><time dateTime={event.occurredAt}>{new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(event.occurredAt))}</time></td></tr>)}</tbody></table></div> : <EmptyState title="No audit events in this scope" description="Committed corporate commands will appear here with actor and version evidence." />}</CorporatePanel>}</div>;
}
