import { CORPORATE_BUNDLE_LABELS, hasCorporatePermission } from "@/src/features/corporate/authorization";
import { CorporatePageHeader, CorporatePanel, EmptyState, ErrorState, FilterBar, PermissionState, StatusBadge } from "@/src/components/corporate/corporate-ui";
import { requireCorporateSession } from "@/src/features/corporate/session";
import { getCorporateStorage } from "@/src/features/corporate/storage";
import { AccessStatusForm } from "@/src/components/corporate/access-status-form";

export default async function AccessAdministrationPage() {
  const session = await requireCorporateSession(); if (!hasCorporatePermission(session, "MANAGE_ACCESS")) return <PermissionState />;
  const people = await getCorporateStorage().getPeople(session).catch(() => null);
  return <div className="corporate-main-stack"><CorporatePageHeader eyebrow="Identity governance" title="Access" description="Review effective bundles and scopes. Broader grants require reviewed provisioning; existing access can be suspended or reinstated here." />{!people ? <ErrorState title="Access records could not be loaded" description="Membership data is unavailable. No access was changed." retryHref="/corporate/administration/access" /> : <CorporatePanel title="Corporate memberships" description="Every change rechecks the target scope, returns assigned work to its team, records an audit event, and attempts session revocation."><FilterBar resultCount={people.length}><label className="corporate-field"><span>Search people</span><input type="search" placeholder="Name or verified email" /></label><label className="corporate-field"><span>Status</span><select><option>All statuses</option><option>Active</option><option>Invited</option><option>Suspended</option></select></label></FilterBar>{people.length ? <div className="corporate-table-region" role="region" aria-label="Corporate membership records" tabIndex={0}><table className="corporate-table"><caption className="sr-only">Corporate access memberships</caption><thead><tr><th scope="col">Person</th><th scope="col">Status</th><th scope="col">Bundles</th><th scope="col">Scope</th><th scope="col">Version</th><th scope="col">Access action</th></tr></thead><tbody>{people.map((person) => <tr key={person.id}><th scope="row"><small>{person.email}</small><strong>{person.displayName}</strong></th><td><StatusBadge tone={person.status === "ACTIVE" ? "success" : person.status === "SUSPENDED" ? "danger" : "waiting"}>{person.status}</StatusBadge></td><td>{person.memberships.map((membership) => CORPORATE_BUNDLE_LABELS[membership.bundle]).join(", ") || "None"}</td><td>{person.memberships.map((membership) => membership.scope.type).join(", ") || "None"}</td><td>{person.version}</td><td>{person.id === session.userId ? <span className="corporate-table-note">Current account</span> : <AccessStatusForm targetUserId={person.id} displayName={person.displayName} currentStatus={person.status} expectedVersion={person.version} />}</td></tr>)}</tbody></table></div> : <EmptyState title="No membership records in this scope" description="Corporate identities appear after the server-owned registry grants access." />}</CorporatePanel>}</div>;
}
