import { notFound } from "next/navigation";
import { CorporateBreadcrumbs, CorporatePageHeader, CorporatePanel, DefinitionList, ErrorState, StatusBadge } from "@/src/components/corporate/corporate-ui";
import { requireCorporateSession } from "@/src/features/corporate/session";
import { getCorporateOrder } from "@/src/features/corporate/operations-data";
import { getOrderAcceptanceState, getOrderCancellationState, getOrderFulfillmentState, getOrderIntegrationState, getOrderPaymentState } from "@/src/features/corporate/orders/state";
import { getLiveLineQuantity, getRemainingLineQuantity } from "@/src/features/corporate/orders/invariants";
import { hasCorporatePermission } from "@/src/features/corporate/authorization";
import { OrderReconciliationForm } from "@/src/components/corporate/order-reconciliation-form";

export default async function CorporateOrderDetailPage({ params }: { params: Promise<{ orderId: string }> }) {
  const session = await requireCorporateSession();
  const { orderId } = await params;
  const order = await getCorporateOrder(session, orderId).catch(() => undefined);
  if (order === undefined) return <ErrorState title="Order could not be loaded" description="The corporate order source is unavailable. No fulfillment or supplier outcome is inferred." retryHref="/corporate/orders" />;
  if (!order) notFound();
  const dimensions = [["Acceptance", getOrderAcceptanceState(order.acceptanceState)], ["Fulfillment", getOrderFulfillmentState(order.fulfillmentState)], ["Payment", getOrderPaymentState(order.paymentState)], ["Integration", getOrderIntegrationState(order.integrationState)], ["Cancellation", getOrderCancellationState(order.cancellationState)]] as const;
  return <div className="corporate-main-stack">
    <CorporateBreadcrumbs items={[{ label: "Orders", href: "/corporate/orders" }, { label: order.sourceOrderId || order.id }]} />
    <CorporatePageHeader eyebrow={`Order · ${order.sourceOrderId || order.id}`} title={`Supply order for ${order.locationName}`} description="Acceptance, fulfillment, payment, integration, and cancellation remain independent facts." actions={<StatusBadge tone="waiting">Source review required</StatusBadge>} />
    <CorporatePanel title="Recorded context" eyebrow="Portal record" description="This is an internal portal order request. It is not supplier, carrier, or finance confirmation."><div className="corporate-detail-body"><DefinitionList items={[{ label: "Location", value: order.locationName }, { label: "Supplier", value: order.supplierLabel || "Not configured" }, { label: "Portal status", value: order.portalStatus || "Unavailable" }, { label: "Created", value: <time dateTime={order.createdAt}>{new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(new Date(order.createdAt))}</time> }]} /></div></CorporatePanel>
    <div className="corporate-state-grid" aria-label="Independent order states">{dimensions.map(([label, state]) => <section key={label}><span>{label}</span><strong>{state.label}</strong><p>{state.meaning}</p></section>)}</div>
    {order.supplierAcknowledgedAt ? <CorporatePanel title="Supplier acknowledgment" eyebrow="Authoritative supplier evidence" description="This evidence arrived through the authenticated supplier integration endpoint."><div className="corporate-detail-body"><DefinitionList items={[{ label: "Supplier", value: order.supplierLabel || "Supplier source" }, { label: "Reference", value: order.acceptanceReference || "Unavailable" }, { label: "Acknowledged", value: <time dateTime={order.supplierAcknowledgedAt}>{new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(order.supplierAcknowledgedAt))}</time> }, { label: "Reconciliation", value: order.reconciliationStatus || "Pending" }]} /></div>{!order.reconciledAt && hasCorporatePermission(session, "COORDINATE_ORDERS", { locationId: order.locationId, organizationId: order.organizationId, regionId: order.regionId }) ? <OrderReconciliationForm locationId={order.locationId} orderId={order.sourceOrderId || order.id} expectedVersion={order.procurementVersion} /> : null}</CorporatePanel> : null}
    <CorporatePanel title="Order lines" eyebrow="Recorded quantities" description="Shipment, delivery, and cancellation quantities remain zero until an authoritative source records them."><div className="corporate-table-region" role="region" aria-label="Order line quantities" tabIndex={0}><table className="corporate-table"><caption className="sr-only">Order lines and independently recorded quantities</caption><thead><tr><th scope="col">Item</th><th scope="col">Ordered</th><th scope="col">Accepted</th><th scope="col">Shipped</th><th scope="col">Delivered</th><th scope="col">Cancelled</th><th scope="col">Outstanding</th><th scope="col">Unit price</th></tr></thead><tbody>{order.lines.map((line) => <tr key={line.sku}><th scope="row"><small>{line.sku}</small><strong>{line.name}</strong></th><td>{line.orderedQuantity}</td><td>{line.acceptedQuantity ?? "Unknown"}</td><td>{line.shippedQuantity}</td><td>{line.deliveredQuantity ?? 0}</td><td>{line.cancelledQuantity ?? 0}</td><td>{getRemainingLineQuantity(line)}</td><td className="corporate-tabular">${line.unitPrice.toFixed(2)}</td></tr>)}</tbody></table></div></CorporatePanel>
    <CorporatePanel title="Recovery" eyebrow="Owned next steps" description="No retry or state change is offered until the owning commercial sources and cancellation policy are configured."><ul className="corporate-recovery-list">{order.recoveryActions.map((action) => <li key={action.label}><strong>{action.label}</strong><span>{action.description}</span></li>)}<li><strong>Reconcile quantities</strong><span>{order.lines.reduce((total, line) => total + getLiveLineQuantity(line), 0)} recorded cases or packs require source-backed acceptance and fulfillment facts.</span></li></ul></CorporatePanel>
  </div>;
}
