import { defineArrayMember, defineField, defineType } from "sanity";

export const homepage = defineType({
  name: "homepage",
  title: "Home Page",
  type: "document",
  groups: [
    { name: "seo", title: "SEO" },
    { name: "hero", title: "Hero" },
    { name: "advantage", title: "Advantage" },
    { name: "candidate", title: "Candidate profile" },
    { name: "cta", title: "Closing CTA" },
  ],
  fields: [
    defineField({ name: "seo", type: "seo", group: "seo", validation: (rule) => rule.required() }),
    defineField({ name: "hero", title: "Hero", type: "object", group: "hero", fields: [
      defineField({ name: "eyebrow", type: "string", validation: (rule) => rule.required().max(60) }),
      defineField({ name: "headline", type: "string", validation: (rule) => rule.required().max(80) }),
      defineField({ name: "description", type: "text", rows: 3, validation: (rule) => rule.required().max(220) }),
      defineField({ name: "desktopImage", type: "imageWithAlt", validation: (rule) => rule.required() }),
      defineField({ name: "mobileImage", type: "imageWithAlt", validation: (rule) => rule.required() }),
      defineField({
        name: "heroProofRail",
        title: "Three-item proof rail",
        description: "Exactly three concise proof points shown beneath the desktop hero actions.",
        type: "array",
        of: [defineArrayMember({
          type: "object",
          fields: [
            defineField({ name: "label", type: "string", validation: (rule) => rule.required().max(40) }),
            defineField({ name: "value", type: "string", validation: (rule) => rule.required().max(80) }),
          ],
          preview: { select: { title: "label", subtitle: "value" } },
        })],
        validation: (rule) => rule.required().length(3),
      }),
      defineField({ name: "primaryAction", title: "Primary action", type: "link", validation: (rule) => rule.required() }),
      defineField({ name: "secondaryAction", title: "Secondary action", type: "link", validation: (rule) => rule.required() }),
      defineField({ name: "secondaryDetail", title: "Secondary-action detail", type: "string", validation: (rule) => rule.max(80) }),
    ] }),
    defineField({ name: "advantage", title: "Advantage", type: "object", group: "advantage", fields: [
      defineField({ name: "eyebrow", type: "string", validation: (rule) => rule.required() }),
      defineField({ name: "heading", type: "string", validation: (rule) => rule.required() }),
      defineField({ name: "introduction", type: "text", rows: 3, validation: (rule) => rule.required() }),
      defineField({
        name: "featuredProofCards",
        title: "Featured proof cards",
        description: "The two large image-led cards at the top of the Advantage section.",
        type: "array",
        of: [defineArrayMember({
          type: "object",
          fields: [
            defineField({ name: "category", type: "string", validation: (rule) => rule.required().max(30) }),
            defineField({ name: "headline", type: "string", validation: (rule) => rule.required().max(90) }),
            defineField({ name: "body", type: "text", rows: 3, validation: (rule) => rule.required().max(220) }),
            defineField({ name: "image", type: "imageWithAlt", validation: (rule) => rule.required() }),
            defineField({ name: "proofPoints", title: "Proof points", type: "stringList", validation: (rule) => rule.required().min(1).max(3) }),
          ],
          preview: { select: { title: "headline", subtitle: "category", media: "image" } },
        })],
        validation: (rule) => rule.required().length(2),
      }),
      defineField({
        name: "outcomesLabel",
        title: "Outcomes divider label",
        type: "string",
        initialValue: "What That Creates",
        validation: (rule) => rule.required().max(50),
      }),
      defineField({
        name: "outcomes",
        title: "Outcomes",
        description: "The two smaller outcome statements beneath the featured proof cards.",
        type: "array",
        of: [defineArrayMember({
          type: "object",
          fields: [
            defineField({ name: "category", type: "string", validation: (rule) => rule.required().max(30) }),
            defineField({ name: "headline", type: "string", validation: (rule) => rule.required().max(90) }),
            defineField({ name: "body", type: "text", rows: 3, validation: (rule) => rule.required().max(220) }),
          ],
          preview: { select: { title: "headline", subtitle: "category" } },
        })],
        validation: (rule) => rule.required().length(2),
      }),
    ] }),
    defineField({ name: "candidateProfile", title: "Candidate profile", type: "object", group: "candidate", fields: [
      defineField({ name: "eyebrow", type: "string", validation: (rule) => rule.required() }),
      defineField({ name: "heading", type: "string", validation: (rule) => rule.required() }),
      defineField({ name: "introduction", type: "text", rows: 3, validation: (rule) => rule.required() }),
      defineField({
        name: "operatorPillars",
        title: "Operator profile pillars",
        description: "The three fixed qualification columns: operating experience, financial readiness, and owner stewardship.",
        type: "array",
        of: [defineArrayMember({
          type: "object",
          fields: [
            defineField({
              name: "kind",
              title: "Pillar",
              type: "string",
              options: { list: [
                { title: "Operating experience", value: "operatingExperience" },
                { title: "Financial readiness", value: "financialReadiness" },
                { title: "Owner stewardship", value: "ownerStewardship" },
              ] },
              validation: (rule) => rule.required(),
            }),
            defineField({ name: "number", type: "string", validation: (rule) => rule.required().regex(/^0[1-3]$/, { name: "two-digit sequence" }) }),
            defineField({ name: "label", type: "string", validation: (rule) => rule.required().max(50) }),
            defineField({ name: "headline", type: "string", validation: (rule) => rule.required().max(90) }),
            defineField({ name: "body", type: "text", rows: 3, validation: (rule) => rule.required().max(220) }),
          ],
          preview: { select: { title: "label", subtitle: "headline" } },
        })],
        validation: (rule) => rule.required().length(3),
      }),
      defineField({ name: "image", type: "imageWithAlt", validation: (rule) => rule.required() }),
      defineField({ name: "imageCaptionTitle", title: "Image caption title", type: "string", validation: (rule) => rule.required().max(80) }),
      defineField({ name: "imageCaption", title: "Image caption", type: "string", validation: (rule) => rule.required().max(140) }),
      defineField({
        name: "partnership",
        title: "Partnership panel",
        type: "object",
        fields: [
          defineField({ name: "eyebrow", type: "string", initialValue: "The partnership", validation: (rule) => rule.required().max(50) }),
          defineField({ name: "heading", type: "string", validation: (rule) => rule.required().max(80) }),
          defineField({ name: "description", type: "text", rows: 4, validation: (rule) => rule.required().max(320) }),
          defineField({ name: "candidateLabel", title: "Candidate contribution label", type: "string", validation: (rule) => rule.required().max(60) }),
          defineField({ name: "candidateItems", title: "What you bring", type: "stringList", validation: (rule) => rule.required().min(1).max(6) }),
          defineField({ name: "brandLabel", title: "Brand contribution label", type: "string", validation: (rule) => rule.required().max(60) }),
          defineField({ name: "brandItems", title: "What Budda's brings", type: "stringList", validation: (rule) => rule.required().min(1).max(6) }),
        ],
      }),
    ] }),
    defineField({ name: "closingCta", title: "Closing CTA", type: "object", group: "cta", fields: [
      defineField({ name: "eyebrow", type: "string", validation: (rule) => rule.required() }),
      defineField({ name: "title", type: "string", validation: (rule) => rule.required() }),
      defineField({ name: "description", type: "text", rows: 3, validation: (rule) => rule.required() }),
      defineField({ name: "primaryAction", type: "link", validation: (rule) => rule.required() }),
      defineField({ name: "secondaryAction", type: "link", validation: (rule) => rule.required() }),
    ] }),
  ],
  preview: { prepare: () => ({ title: "Home Page" }) },
});
